### ISSUE TITLE
Set the auto_update_archive to true by default

### ISSUE THREAD

**Issue by eichblatt** [eichblatt/deadstream#269]
This is not a huge deal, but a lot of people are now using their Time Machines to listen to newer stuff, like John Mayer, Phish, and Ween

It's annoying that they don't get updates unless they know the secret command.

**Comment by Sidahmed-ben** [comment]
hello @eichblatt , the issue interrests me can you assign it to me please. Thank you !

**Comment by eichblatt** [comment]
Done
