### ISSUE TITLE
Lossless playback leads to gaps between tracks (and sometimes skipping within a track)

### ISSUE THREAD

**Issue by weitzner** [eichblatt/deadstream#345]
I am running a pre-built 3A. I’ve seen this behavior documented, but I am wondering if this could be addressed by adjusting the buffer size, allowing (temporary) downloads or some other cute caching trick. Is there a good way to adjust the buffer size on device to test this out? Has any testing like this been performed before? Happy to help out, but might need to be pointed in the right direction!

**Comment by eichblatt** [comment]
Sorry for the delay in replying! I don't check this very often.

Yes, I have only gotten lossless playback to work satisfactorily by connecting to an ethernet cable (which is not possible on a Raspberry Pi 3A+). If you are really determined to get it working, get a Pi 4 or Pi 3B+ and connect it via ethernet cable.

The code doesn't do any caching or downloading of tracks, and that would complicate the code quite a bit. I tried caching early on, but realized that it is very tricky -- easy to get something working, but really hard to know if it is working correctly. Grateful Dead soundboard shows are marked "stream only", (those shows generally do not have lossless versions), so any downloading would only apply to the audience recordings.

**Comment by weitzner** [comment]
Thanks for the detailed response. Unfortunately where I have the pi is likely the most-inconvenient place in my house to run ethernet, so I will stick with what's working!
